# Use an official lightweight Python image.
FROM python:3.9-slim

# Set the working directory inside the container to /app.
WORKDIR /app

# Copy all local files into the container.
COPY . /app

# Install dependencies defined in requirements.txt.
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available outside this container
EXPOSE 5000

# Run the Flask application.
CMD ["python", "app/main.py"]
